### ISSUE TITLE
Add directions widget

### ISSUE THREAD

**Issue by seanerice** [seanerice/clt-bicycle-map#17]
### Purpose
New widget to calculate directions between two points. Points are selected by clicking on the map.

### Todo
- [x] add "Starting position" input field
  - [x] when the input is focused, user can click on the map to set value
- [x] add "Destination" input field
  - [x] when the input is focused, user can click on the map to set value
- [x] Calculate directions once both values are set

### Acceptance Criteria
- verify "Starting position" input field is focused after clicking on the input
- verify "Starting position" input field is populated by clicking on the map
- verify "Starting position" is displayed visually on the map with a marker
- verify "Destination" input field is focused after clicking on the input
- verify "Destination" input field is populated by clicking on the map
- verify "Destination" is displayed visually on the map with a marker
- verify route is calculated once "Starting position" and "Destination" are set
- verify route is displayed visually on the map with a line
- verify that route is re-calculated after updating either "Starting position" or "Destination" input fields

**Comment by seanerice** [comment]
Progress

![Image](https://github.com/seanerice/clt-bicycle-map/assets/5473450/aafaceb0-d61c-4182-b447-399e37010602)
